"""baseline_current_schema

Revision ID: 20260705_0001
Revises:
Create Date: 2026-07-05 15:28:17.896785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260705_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("pib", sa.String(length=20), nullable=True),
        sa.Column("maticni_broj", sa.String(length=20), nullable=True),
        sa.Column("contact", sa.String(length=200), nullable=True),
        sa.Column("client_type", sa.String(length=20), nullable=True),
        sa.Column("document_language", sa.String(length=5), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clients_id"), ["id"], unique=False)

    op.create_table(
        "contribution_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("pio_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("health_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unemployment_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("pay_order_number", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contribution_rates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contribution_rates_id"), ["id"], unique=False)

    op.create_table(
        "eco_tax",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("reminder_sent", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eco_tax", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eco_tax_id"), ["id"], unique=False)

    op.create_table(
        "efaktura_import_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_key", sa.String(length=500), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=False),
        sa.Column("amount_rsd", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=True),
        sa.Column("supplier_pib", sa.String(length=20), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_pib", sa.String(length=20), nullable=True),
        sa.Column("imported_as", sa.String(length=20), nullable=False),
        sa.Column("imported_record_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_key", name="uq_efaktura_document_key"),
    )
    with op.batch_alter_table("efaktura_import_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_efaktura_import_records_document_key"), ["document_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_efaktura_import_records_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_efaktura_import_records_id"), ["id"], unique=False)

    op.create_table(
        "enterprise",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("pib", sa.String(length=20), nullable=True),
        sa.Column("maticni_broj", sa.String(length=20), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("bank_account", sa.String(length=50), nullable=True),
        sa.Column("bank_swift", sa.String(length=20), nullable=True),
        sa.Column("main_activity_code", sa.String(length=20), nullable=True),
        sa.Column("opening_cash_balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("opening_cash_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("emblem_data_url", sa.Text(), nullable=True),
        sa.Column("efaktura_enabled", sa.Boolean(), nullable=True),
        sa.Column("efaktura_api_base_url", sa.String(length=500), nullable=True),
        sa.Column("efaktura_api_key", sa.Text(), nullable=True),
        sa.Column("efaktura_api_key_header", sa.String(length=100), nullable=True),
        sa.Column("efaktura_api_key_prefix", sa.String(length=50), nullable=True),
        sa.Column("efaktura_sync_incoming", sa.Boolean(), nullable=True),
        sa.Column("efaktura_sync_outgoing", sa.Boolean(), nullable=True),
        sa.Column("efaktura_sync_lookback_days", sa.Integer(), nullable=True),
        sa.Column("efaktura_incoming_list_path", sa.String(length=500), nullable=True),
        sa.Column("efaktura_incoming_document_path", sa.String(length=500), nullable=True),
        sa.Column("efaktura_outgoing_list_path", sa.String(length=500), nullable=True),
        sa.Column("efaktura_outgoing_document_path", sa.String(length=500), nullable=True),
        sa.Column("efaktura_save_pdf", sa.Boolean(), nullable=True),
        sa.Column("efaktura_incoming_pdf_path", sa.String(length=500), nullable=True),
        sa.Column("efaktura_outgoing_pdf_path", sa.String(length=500), nullable=True),
        sa.Column("backup_dir", sa.String(length=500), nullable=True),
        sa.Column("backup_auto_enabled", sa.Boolean(), nullable=True),
        sa.Column("backup_auto_interval_hours", sa.Integer(), nullable=True),
        sa.Column("backup_auto_retention_count", sa.Integer(), nullable=True),
        sa.Column("backup_manual_retention_count", sa.Integer(), nullable=True),
        sa.Column("backup_pre_restore_retention_count", sa.Integer(), nullable=True),
        sa.Column("backup_scheduler_check_minutes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("enterprise", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_enterprise_id"), ["id"], unique=False)

    op.create_table(
        "invoice_sequence",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year"),
    )
    op.create_table(
        "payment_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name_sr", sa.String(length=100), nullable=False),
        sa.Column("name_ru", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("payment_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_types_id"), ["id"], unique=False)

    op.create_table(
        "project_sequence",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("default_language", sa.String(length=5), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_id"), ["id"], unique=False)

    op.create_table(
        "bank_import_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("transaction_count", sa.Integer(), nullable=True),
        sa.Column("created_income", sa.Integer(), nullable=True),
        sa.Column("created_expense", sa.Integer(), nullable=True),
        sa.Column("errors_count", sa.Integer(), nullable=True),
        sa.Column("imported_by", sa.Integer(), nullable=True),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bank_import_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_import_files_file_hash"), ["file_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_bank_import_files_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_import_files_imported_at"), ["imported_at"], unique=False)

    op.create_table(
        "counterparty_loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_type", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("counterparty_name", sa.String(length=200), nullable=False),
        sa.Column("agreement_number", sa.String(length=100), nullable=True),
        sa.Column("agreement_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("counterparty_loans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_counterparty_loans_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loans_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loans_loan_type"), ["loan_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loans_start_date"), ["start_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loans_status"), ["status"], unique=False)

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("rates_id", sa.Integer(), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("pio_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("health_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unemployment_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rates_id"],
            ["contribution_rates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_id"), ["id"], unique=False)

    op.create_table(
        "period_closures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=False),
        sa.Column("closed_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("period_closures", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_period_closures_id"), ["id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("planned_income", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("planned_expense", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_projects_code"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_id"), ["id"], unique=False)

    op.create_table(
        "year_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("payment_type_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("monthly_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("base_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rate_percent", sa.Float(), nullable=True),
        sa.Column("recipient_name", sa.String(length=200), nullable=True),
        sa.Column("recipient_account", sa.String(length=30), nullable=False),
        sa.Column("sifra_placanja", sa.String(length=10), nullable=True),
        sa.Column("model", sa.String(length=10), nullable=True),
        sa.Column("poziv_na_broj", sa.String(length=50), nullable=False),
        sa.Column("poziv_na_broj_next", sa.String(length=50), nullable=True),
        sa.Column("payment_purpose", sa.String(length=200), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("is_provisional", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_type_id"],
            ["payment_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("year_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_year_decisions_id"), ["id"], unique=False)

    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("counterparty_name", sa.String(length=200), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("bank_reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("matched_type", sa.String(length=50), nullable=True),
        sa.Column("matched_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_reference"),
    )
    with op.batch_alter_table("bank_transactions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_transactions_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_transactions_direction"), ["direction"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_transactions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_transactions_status"), ["status"], unique=False)

    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("contract_type", sa.String(length=50), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("validity_start", sa.Date(), nullable=True),
        sa.Column("validity_end", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contracts_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contracts_project_id"), ["project_id"], unique=False)

    op.create_table(
        "transaction_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=100), nullable=False),
        sa.Column("name_sr", sa.String(length=100), nullable=False),
        sa.Column("category_type", sa.String(length=20), nullable=True),
        sa.Column("category_group", sa.String(length=20), nullable=True),
        sa.Column("default_project_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transaction_categories_id"), ["id"], unique=False)

    op.create_table(
        "contract_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contract_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contract_items_id"), ["id"], unique=False)

    op.create_table(
        "counterparty_loan_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["counterparty_loans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("counterparty_loan_movements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_counterparty_loan_movements_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loan_movements_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_counterparty_loan_movements_loan_id"), ["loan_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_counterparty_loan_movements_movement_type"), ["movement_type"], unique=False
        )
        batch_op.create_index(
            "ux_counterparty_loan_movements_bank_transaction_id_not_null",
            ["bank_transaction_id"],
            unique=True,
            sqlite_where=sa.text("bank_transaction_id IS NOT NULL"),
            postgresql_where=sa.text("bank_transaction_id IS NOT NULL"),
        )

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("bank_reference", sa.String(length=100), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_tax_related", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("reversed_expense_id", sa.Integer(), nullable=True),
        sa.Column("reversal_of_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["transaction_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversed_expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expenses_id"), ["id"], unique=False)

    op.create_table(
        "income",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("invoice_year", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("client_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("amount_rsd", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paid_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("income_type", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("contract_payment_type", sa.String(length=20), nullable=True),
        sa.Column("bank_reference", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_year", "invoice_number", name="uq_income_invoice_per_year"),
    )
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_income_id"), ["id"], unique=False)

    op.create_table(
        "workers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("worker_type", sa.String(length=20), nullable=False),
        sa.Column("pay_scheme", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("regular_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("weekly_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monthly_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_pricing_mode", sa.String(length=30), nullable=False),
        sa.Column("trip_work_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_per_diem_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_food_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_advance_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lodging_night_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lodging_nights_offset", sa.Integer(), nullable=True),
        sa.Column("default_project_id", sa.Integer(), nullable=True),
        sa.Column("default_category_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["transaction_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workers_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workers_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_workers_name"), ["name"], unique=False)

    op.create_table(
        "bank_transaction_income_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=False),
        sa.Column("income_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["income_id"],
            ["income.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_transaction_id", "income_id", name="uq_bank_tx_income_allocation"),
    )
    with op.batch_alter_table("bank_transaction_income_allocations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bank_transaction_income_allocations_bank_transaction_id"),
            ["bank_transaction_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_bank_transaction_income_allocations_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_bank_transaction_income_allocations_income_id"), ["income_id"], unique=False
        )

    op.create_table(
        "cash_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_transaction_id"),
        sa.UniqueConstraint("expense_id"),
    )
    with op.batch_alter_table("cash_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cash_entries_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_cash_entries_direction"), ["direction"], unique=False)
        batch_op.create_index(batch_op.f("ix_cash_entries_entry_type"), ["entry_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_cash_entries_id"), ["id"], unique=False)

    op.create_table(
        "expense_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expense_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expense_items_expense_id"), ["expense_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_expense_items_id"), ["id"], unique=False)

    op.create_table(
        "income_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("income_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_category", sa.String(length=20), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["income_id"], ["income.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("income_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_income_items_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_income_items_income_id"), ["income_id"], unique=False)

    op.create_table(
        "incoming_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("counterparty_name", sa.String(length=200), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("settled_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("efaktura_record_id", sa.Integer(), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("advance_invoice_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advance_invoice_id"],
            ["incoming_invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["efaktura_record_id"],
            ["efaktura_import_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("efaktura_record_id"),
        sa.UniqueConstraint("expense_id"),
    )
    with op.batch_alter_table("incoming_invoices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incoming_invoices_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_incoming_invoices_id"), ["id"], unique=False)

    op.create_table(
        "monthly_obligations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("payment_type_id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["year_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_type_id"],
            ["payment_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monthly_obligations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monthly_obligations_id"), ["id"], unique=False)

    op.create_table(
        "planned_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("worker_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(length=20), nullable=True),
        sa.Column("payment_day", sa.Integer(), nullable=True),
        sa.Column("payment_day_of_week", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("reminder_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["transaction_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("planned_expenses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_planned_expenses_id"), ["id"], unique=False)

    op.create_table(
        "incoming_invoice_settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incoming_invoice_id", sa.Integer(), nullable=False),
        sa.Column("settlement_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("cash_entry_id", sa.Integer(), nullable=True),
        sa.Column("income_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cash_entry_id"],
            ["cash_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["income_id"],
            ["income.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incoming_invoice_id"],
            ["incoming_invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incoming_invoice_settlements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incoming_invoice_settlements_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incoming_invoice_settlements_incoming_invoice_id"), ["incoming_invoice_id"], unique=False
        )

    op.create_table(
        "purchase_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("verification_url", sa.Text(), nullable=False),
        sa.Column("qr_hash", sa.String(length=64), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column("token", sa.String(length=100), nullable=True),
        sa.Column("seller_name", sa.String(length=200), nullable=True),
        sa.Column("seller_tax_id", sa.String(length=20), nullable=True),
        sa.Column("seller_address", sa.String(length=500), nullable=True),
        sa.Column("seller_city", sa.String(length=100), nullable=True),
        sa.Column("receipt_datetime", sa.DateTime(), nullable=True),
        sa.Column("payment_type", sa.String(length=100), nullable=True),
        sa.Column("payment_kind", sa.String(length=20), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("cash_entry_id", sa.Integer(), nullable=True),
        sa.Column("raw_html", sa.Text(), nullable=True),
        sa.Column("raw_specifications_json", sa.Text(), nullable=True),
        sa.Column("raw_recapitulation_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cash_entry_id"],
            ["cash_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["transaction_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("expense_id"),
        sa.UniqueConstraint("qr_hash", name="uq_purchase_receipts_qr_hash"),
    )
    with op.batch_alter_table("purchase_receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_receipts_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_receipts_invoice_number"), ["invoice_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_receipts_qr_hash"), ["qr_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_purchase_receipts_receipt_datetime"), ["receipt_datetime"], unique=False)

    op.create_table(
        "worker_payouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("cash_entry_id", sa.Integer(), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("payout_type", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("work_days", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("trip_days", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("lodging_nights", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("regular_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("weekly_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monthly_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_pricing_mode", sa.String(length=30), nullable=False),
        sa.Column("trip_work_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_per_diem_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_food_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("trip_advance_day_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lodging_night_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lodging_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("advance_paid", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("gross_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_paid_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remaining_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cash_entry_id"],
            ["cash_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["transaction_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cash_entry_id"),
        sa.UniqueConstraint("expense_id"),
    )
    with op.batch_alter_table("worker_payouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_worker_payouts_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_worker_payouts_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_worker_payouts_payout_type"), ["payout_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_worker_payouts_worker_id"), ["worker_id"], unique=False)

    op.create_table(
        "planned_expense_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planned_expense_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=False),
        sa.Column("worker_payout_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["planned_expense_id"],
            ["planned_expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_payout_id"],
            ["worker_payouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("planned_expense_payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_planned_expense_payments_id"), ["id"], unique=False)

    op.create_table(
        "purchase_receipt_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("gtin", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=True),
        sa.Column("label_rate", sa.Float(), nullable=True),
        sa.Column("tax_base_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vat_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["purchase_receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_receipt_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_receipt_items_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_receipt_items_receipt_id"), ["receipt_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_receipt_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_receipt_items_receipt_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_receipt_items_id"))

    op.drop_table("purchase_receipt_items")
    with op.batch_alter_table("planned_expense_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_planned_expense_payments_id"))

    op.drop_table("planned_expense_payments")
    with op.batch_alter_table("worker_payouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_worker_payouts_worker_id"))
        batch_op.drop_index(batch_op.f("ix_worker_payouts_payout_type"))
        batch_op.drop_index(batch_op.f("ix_worker_payouts_id"))
        batch_op.drop_index(batch_op.f("ix_worker_payouts_date"))

    op.drop_table("worker_payouts")
    with op.batch_alter_table("purchase_receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_receipts_receipt_datetime"))
        batch_op.drop_index(batch_op.f("ix_purchase_receipts_qr_hash"))
        batch_op.drop_index(batch_op.f("ix_purchase_receipts_invoice_number"))
        batch_op.drop_index(batch_op.f("ix_purchase_receipts_id"))

    op.drop_table("purchase_receipts")
    with op.batch_alter_table("incoming_invoice_settlements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incoming_invoice_settlements_incoming_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_incoming_invoice_settlements_id"))

    op.drop_table("incoming_invoice_settlements")
    with op.batch_alter_table("planned_expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_planned_expenses_id"))

    op.drop_table("planned_expenses")
    with op.batch_alter_table("monthly_obligations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monthly_obligations_id"))

    op.drop_table("monthly_obligations")
    with op.batch_alter_table("incoming_invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incoming_invoices_id"))
        batch_op.drop_index(batch_op.f("ix_incoming_invoices_date"))

    op.drop_table("incoming_invoices")
    with op.batch_alter_table("income_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_items_income_id"))
        batch_op.drop_index(batch_op.f("ix_income_items_id"))

    op.drop_table("income_items")
    with op.batch_alter_table("expense_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_items_id"))
        batch_op.drop_index(batch_op.f("ix_expense_items_expense_id"))

    op.drop_table("expense_items")
    with op.batch_alter_table("cash_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cash_entries_id"))
        batch_op.drop_index(batch_op.f("ix_cash_entries_entry_type"))
        batch_op.drop_index(batch_op.f("ix_cash_entries_direction"))
        batch_op.drop_index(batch_op.f("ix_cash_entries_date"))

    op.drop_table("cash_entries")
    with op.batch_alter_table("bank_transaction_income_allocations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_transaction_income_allocations_income_id"))
        batch_op.drop_index(batch_op.f("ix_bank_transaction_income_allocations_id"))
        batch_op.drop_index(batch_op.f("ix_bank_transaction_income_allocations_bank_transaction_id"))

    op.drop_table("bank_transaction_income_allocations")
    with op.batch_alter_table("workers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workers_name"))
        batch_op.drop_index(batch_op.f("ix_workers_is_active"))
        batch_op.drop_index(batch_op.f("ix_workers_id"))

    op.drop_table("workers")
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_id"))

    op.drop_table("income")
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_id"))

    op.drop_table("expenses")
    with op.batch_alter_table("counterparty_loan_movements", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_counterparty_loan_movements_bank_transaction_id_not_null",
            sqlite_where=sa.text("bank_transaction_id IS NOT NULL"),
            postgresql_where=sa.text("bank_transaction_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_counterparty_loan_movements_movement_type"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loan_movements_loan_id"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loan_movements_id"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loan_movements_date"))

    op.drop_table("counterparty_loan_movements")
    with op.batch_alter_table("contract_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contract_items_id"))

    op.drop_table("contract_items")
    with op.batch_alter_table("transaction_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_categories_id"))

    op.drop_table("transaction_categories")
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contracts_project_id"))
        batch_op.drop_index(batch_op.f("ix_contracts_id"))

    op.drop_table("contracts")
    with op.batch_alter_table("bank_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_transactions_status"))
        batch_op.drop_index(batch_op.f("ix_bank_transactions_id"))
        batch_op.drop_index(batch_op.f("ix_bank_transactions_direction"))
        batch_op.drop_index(batch_op.f("ix_bank_transactions_date"))

    op.drop_table("bank_transactions")
    with op.batch_alter_table("year_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_year_decisions_id"))

    op.drop_table("year_decisions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_id"))

    op.drop_table("projects")
    with op.batch_alter_table("period_closures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_period_closures_id"))

    op.drop_table("period_closures")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_id"))

    op.drop_table("payments")
    with op.batch_alter_table("counterparty_loans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_counterparty_loans_status"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loans_start_date"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loans_loan_type"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loans_id"))
        batch_op.drop_index(batch_op.f("ix_counterparty_loans_client_id"))

    op.drop_table("counterparty_loans")
    with op.batch_alter_table("bank_import_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_import_files_imported_at"))
        batch_op.drop_index(batch_op.f("ix_bank_import_files_id"))
        batch_op.drop_index(batch_op.f("ix_bank_import_files_file_hash"))

    op.drop_table("bank_import_files")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_id"))

    op.drop_table("users")
    op.drop_table("project_sequence")
    with op.batch_alter_table("payment_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_types_id"))

    op.drop_table("payment_types")
    op.drop_table("invoice_sequence")
    with op.batch_alter_table("enterprise", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enterprise_id"))

    op.drop_table("enterprise")
    with op.batch_alter_table("efaktura_import_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_efaktura_import_records_id"))
        batch_op.drop_index(batch_op.f("ix_efaktura_import_records_external_id"))
        batch_op.drop_index(batch_op.f("ix_efaktura_import_records_document_key"))

    op.drop_table("efaktura_import_records")
    with op.batch_alter_table("eco_tax", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eco_tax_id"))

    op.drop_table("eco_tax")
    with op.batch_alter_table("contribution_rates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contribution_rates_id"))

    op.drop_table("contribution_rates")
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clients_id"))

    op.drop_table("clients")
    # ### end Alembic commands ###
